name: 'Retry command'
description: 'Retries an Action step on failure.'
author: 'corrupt952'

inputs:
  command:
    description: 'The command to run'
    required: true
  working_directory:
    description: 'The directory in which to execute the command'
    required: true
    default: '.'
  max_attempts:
    description: 'The maximum number of times to attempt the command'
    required: true
    default: '5'
  retry_interval:
    description: 'The time to wait between retry attempts, in seconds'
    required: true
    default: '5'

outputs:
  exit_code:
    description: 'Exit code of the last command executed'
  result:
    description: 'Output of the last command executed'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'repeat'
  color: 'blue'
